import type { EditorThemeClasses } from "lexical";

/** Tailwind classes Lexical applies to the nodes it renders. */
export const editorTheme: EditorThemeClasses = {
  // Lexical hides the native caret beside block decorators and uses this cursor.
  blockCursor:
    "pointer-events-none relative block h-0 before:absolute before:top-0 before:left-0 before:h-7 before:w-px before:animate-caret-blink before:bg-foreground",
  paragraph: "mb-3 leading-7",
  quote: "mb-3 border-l-2 border-border pl-4 text-muted-foreground italic",
  heading: {
    h1: "mb-4 text-3xl font-bold tracking-tight text-heading-1",
    h2: "mb-3 text-2xl font-semibold tracking-tight text-heading-2",
    h3: "mb-3 text-xl font-semibold text-heading-3",
    h4: "mb-2 text-lg font-semibold",
    h5: "mb-2 font-semibold",
    h6: "mb-2 text-sm font-semibold",
  },
  list: {
    ul: "mb-3 ml-4 list-disc",
    ol: "mb-3 ml-6 list-decimal",
    listitem: "my-1",
    checklist: "editor-checklist mb-3 list-none",
    listitemChecked: "editor-checklist-item editor-checklist-checked",
    listitemUnchecked: "editor-checklist-item",
    nested: { listitem: "list-none" },
  },
  link: "text-primary underline underline-offset-4",
  hr: "my-4 border-0 border-t border-border",
  hrSelected: "outline outline-ring",
  code: "mb-3 block overflow-x-auto rounded-md bg-muted p-3 font-code text-sm",
  codeHighlight: {
    atrule: "text-syntax-keyword",
    attr: "text-syntax-function",
    "attr-name": "text-syntax-function",
    "attr-value": "text-syntax-string",
    boolean: "text-syntax-number",
    builtin: "text-syntax-function",
    cdata: "text-syntax-comment",
    char: "text-syntax-string",
    "class-name": "text-syntax-type",
    comment: "text-syntax-comment",
    constant: "text-syntax-number",
    deleted: "text-destructive",
    doctype: "text-syntax-comment",
    entity: "text-syntax-number",
    function: "text-syntax-function",
    important: "text-syntax-keyword",
    inserted: "text-syntax-string",
    keyword: "text-syntax-keyword",
    namespace: "text-syntax-type",
    number: "text-syntax-number",
    operator: "text-syntax-operator",
    prolog: "text-syntax-comment",
    property: "text-syntax-function",
    punctuation: "text-syntax-operator",
    regex: "text-syntax-string",
    selector: "text-syntax-keyword",
    string: "text-syntax-string",
    symbol: "text-syntax-number",
    tag: "text-syntax-keyword",
    url: "text-syntax-string",
    variable: "text-syntax-type",
  },
  table: "mb-3 w-full border-collapse text-sm",
  tableRow: "border-b border-border",
  tableCell: "min-w-24 border border-border px-3 py-2 align-top",
  tableCellHeader: "bg-popover font-semibold",
  tableCellSelected: "bg-accent",
  tableSelection: "selection:bg-transparent",
  tableScrollableWrapper: "editor-scrollbar w-full overflow-x-auto",
  text: {
    bold: "font-bold",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline",
    code: "rounded bg-muted px-1 py-0.5 font-code text-sm",
  },
};
